### ISSUE TITLE
New Bugfix release 1.2.2

### ISSUE THREAD

**Issue by bitzl** [nfroidure/streamtest#3]
There have been several minor Bugfixes and fixes to the documentation/README.md. The new README.md won't show up on https://www.npmjs.com/package/streamtest until we refresh the package or make a new release.

As the package is associated with @nfroidure's account on npmjs.com, I probably can't do this. Therefore, there are several options:
- @nfroidure creates the new release and publishes to NPM
- @bitzl gets assigned on NPM ([@marcus.bitzl](https://www.npmjs.com/~marcus.bitzl)) to the package, creates the new release and publishes to NPM

@nfroidure we can discuss this also via Email or Gitter, if you prefer.

**Comment by nfroidure** [comment]
@bitzl i added you to the NPM publishers, your help is welcome ;).

**Comment by bitzl** [comment]
Done.
